# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Nick Nance
tagline:             'Code and Architecture in Javascript'
description:         'Passionate about solving business problems with modern web technologies and open source'
url:                 http://staging.nnance.me
baseurl:             /
paginate:            5

# Build
future: false
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Nick Nance
  url:               https://twitter.com/nancenick
  email:             nance.nick@gmail.com

# Custom vars
version:             1.0.0
