# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Nick Nance
tagline:             "Let's build it together"
description:         'Passionate about solving business problems with modern web technologies and open source. <a href="https://twitter.com/nancenick">@nancenick</a>'
url:                 http://nnance.me
baseurl:             http://nnance.github.io/
paginate:            5

# About/contact
author:
  name:              Nick Nance
  url:               https://twitter.com/nancenick
  email:             nance.nick@gmail.com

# Custom vars
version:             1.0.0
